server:
  port: 8093
spring:
  application:
    name: apiservice
  profiles:
    active: db
#Eureka Server Registration
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${DISCOVERY_SERVICE}:8091/eureka