version: "3.7"
services:
  dbservice:
    container_name: dbservice
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - ./db.env
#    restart:
#      on-failure
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data
    networks:
      - microservices
  discoveryservice:
    container_name: discoveryservice
    build: ./discoveryservice
    ports:
      - 8091:8091
    env_file:
      - ./microservice.env
      - ./db.env
#    restart:
#      on-failure
    networks:
      - microservices
  authservice:
    container_name: authservice
    build: ./authservice
    ports:
      - 8092:8092
    env_file:
      - ./microservice.env
      - ./db.env
#    restart:
#      on-failure
    depends_on:
      - dbservice
      - discoveryservice
    networks:
      - microservices
  apiservice:
    container_name: apiservice
    build: ./apiservice
    ports:
      - 8093:8093
    env_file:
      - ./microservice.env
      - ./db.env
#    restart:
#      on-failure
    depends_on:
      - dbservice
      - discoveryservice
    networks:
      - microservices
  gatewayservice:
    container_name: gatewayservice
    build: ./gatewayservice
    ports:
      - 8090:8090
    env_file:
      - ./microservice.env
#    restart:
#      on-failure
    depends_on:
      - discoveryservice
    networks:
      - microservices
  monitoringservice:
    container_name: monitoringservice
    build: ./monitoringservice
    ports:
      - 8095:8095
    env_file:
      - ./microservice.env
#    restart:
#      on-failure
    networks:
      - microservices
networks:
  microservices:
    driver: bridge