server:
  port: 8092
spring:
  application:
    name: authservice
  boot:
    admin:
      client:
        url: ${MONITORING_SERVICE:http://localhost:8095}
#Eureka Server Registration
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8091/eureka}
    enabled: true
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always