hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  application:
    name: gatewayservice
  boot:
    admin:
      client:
        url: ${MONITORING_SERVICE:http://localhost:8095}
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8091/eureka}
    enabled: true
  instance:
    preferIpAddress: true
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always