#Database Connection
spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:localhost}:${DB_SERVICE_PORT:5432}/${POSTGRES_DB:microservices}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800
      leak-detection-threshold: 600000
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update