server:
  port: 8091
spring:
  application:
    name: discoveryservice
  boot:
    admin:
      client:
        url: ${MONITORING_SERVICE:http://localhost:8095}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8091/eureka}